### ISSUE TITLE
Middle alingment

### ISSUE THREAD

**Issue by BlueMystical** [Sphinxxxx/vanilla-picker#52]
Not an issue but a suggestion:

Add a 'middle' alignment for the popup:
`popup: 'middle',        //<- 'top' | 'bottom' | 'left' | 'right' | 'middle' | false`

This can easily be done by adding this to the CSS:
```css
/* Middle positioning */
.popup.popup_middle {
    top: 0;
    right: 50%;
}
.popup.popup_middle .picker_arrow {
	top: 0;
	right: 0;
	-webkit-transform: scale(-1, 1);
	transform: scale(-1, 1)
}
```
End results:
![Image](https://github.com/user-attachments/assets/967efbdc-e04b-4b72-a452-50cdfa877ca3)
